"""
===============================================================================
Module      : confidence_engine.py
Project     : PulseViper XAU AI
Version     : 1.0
Author      : Muhammad Adnan
Purpose     : Institutional Trade Confidence Engine
===============================================================================
"""

from __future__ import annotations

from typing import Any

from numbers import Real

import pandas as pd


class ConfidenceEngine:
    """
    Combines existing market evidence into a normalized
    0-100 trade confidence score.

    This engine does NOT create new market signals.
    It only evaluates signals already generated by
    upstream engines.
    """

    def __init__(
        self,
        fvg_weight: float = 25.0,
        displacement_weight: float = 20.0,
        bos_weight: float = 20.0,
        liquidity_weight: float = 15.0,
        structure_weight: float = 10.0,
        mitigation_weight: float = 10.0,
    ) -> None:

        self.fvg_weight = float(fvg_weight)
        self.displacement_weight = float(displacement_weight)
        self.bos_weight = float(bos_weight)
        self.liquidity_weight = float(liquidity_weight)
        self.structure_weight = float(structure_weight)
        self.mitigation_weight = float(mitigation_weight)

        self.total_weight = (
            self.fvg_weight
            + self.displacement_weight
            + self.bos_weight
            + self.liquidity_weight
            + self.structure_weight
            + self.mitigation_weight
        )

        if self.total_weight <= 0.0:
            raise ValueError(
                "Confidence weights must have a positive total."
            )

    # =========================================================================
    # Safe conversion helpers
    # =========================================================================

    @staticmethod
    def _to_float(
        value: Any,
        default: float = 0.0,
    ) -> float:
        """
        Safely convert Python, NumPy, and Pandas numeric
        scalar values to float.
        """

        if value is None:
            return default

        if isinstance(value, bool):
            return float(value)

        if isinstance(value, Real):
            return float(value)

        if isinstance(value, str):
            try:
                return float(value)
            except ValueError:
                return default

        try:
            converted = float(value)
        except (TypeError, ValueError):
            return default

        return converted

    @staticmethod
    def _clamp(
        value: float,
        minimum: float = 0.0,
        maximum: float = 100.0,
    ) -> float:
        """
        Clamp numeric value to a defined range.
        """

        return max(
            minimum,
            min(
                maximum,
                value,
            ),
        )

    # =========================================================================
    # Required columns
    # =========================================================================

    @staticmethod
    def _ensure_columns(
        df: pd.DataFrame,
    ) -> None:

        required_columns = [
            "close",
        ]

        missing = [
            column
            for column in required_columns
            if column not in df.columns
        ]

        if missing:
            raise ValueError(
                f"Missing required confidence columns: {missing}"
            )

    # =========================================================================
    # FVG evidence
    # =========================================================================

    def _fvg_score(
        self,
        row: pd.Series,
    ) -> float:
        """
        Read FVG quality score generated by FVGQualityEngine.
        """

        if "fvg_quality_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["fvg_quality_score"]
                )
            )

        return 0.0

    # =========================================================================
    # Displacement evidence
    # =========================================================================

    def _displacement_score(
        self,
        row: pd.Series,
    ) -> float:
        """
        Read displacement evidence.
        """

        if "fvg_displacement_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["fvg_displacement_score"]
                )
            )

        if "displacement_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["displacement_score"]
                )
            )

        if "is_displacement" in row.index:

            signal = self._to_float(
                row["is_displacement"]
            )

            if signal == 1.0:
                return 100.0

        return 0.0

    # =========================================================================
    # BOS evidence
    # =========================================================================

    def _bos_score(
        self,
        row: pd.Series,
    ) -> float:
        """
        Evaluate Break Of Structure evidence.
        """

        if "fvg_bos_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["fvg_bos_score"]
                )
            )

        bullish_bos = self._to_float(
            row["bullish_bos"]
            if "bullish_bos" in row.index
            else 0.0
        )

        bearish_bos = self._to_float(
            row["bearish_bos"]
            if "bearish_bos" in row.index
            else 0.0
        )

        if bullish_bos == 1.0 or bearish_bos == 1.0:

            strength = self._to_float(
                row["bos_strength"]
                if "bos_strength" in row.index
                else 0.0
            )

            return self._clamp(
                50.0 + (
                    strength * 50.0
                )
            )

        return 0.0

    # =========================================================================
    # Liquidity evidence
    # =========================================================================

    def _liquidity_score(
        self,
        row: pd.Series,
    ) -> float:
        """
        Evaluate liquidity sweep evidence.
        """

        if "fvg_liquidity_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["fvg_liquidity_score"]
                )
            )

        liquidity_columns = [
            "liquidity_sweep",
            "bullish_sweep",
            "bearish_sweep",
            "liquidity_swept",
        ]

        for column in liquidity_columns:

            if column not in row.index:
                continue

            value = self._to_float(
                row[column]
            )

            if value == 1.0:
                return 100.0

        return 0.0

    # =========================================================================
    # Structure evidence
    # =========================================================================

    def _structure_score(
        self,
        row: pd.Series,
    ) -> float:
        """
        Evaluate market structure evidence.
        """

        if "fvg_structure_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["fvg_structure_score"]
                )
            )

        structure_columns = [
            "HH",
            "HL",
            "LH",
            "LL",
        ]

        for column in structure_columns:

            if column not in row.index:
                continue

            value = self._to_float(
                row[column]
            )

            if value == 1.0:
                return 100.0

        return 0.0

    # =========================================================================
    # Mitigation evidence
    # =========================================================================

    def _mitigation_score(
        self,
        row: pd.Series,
    ) -> float:
        """
        Evaluate FVG mitigation/rejection evidence.
        """

        if "fvg_mitigation_score" in row.index:

            return self._clamp(
                self._to_float(
                    row["fvg_mitigation_score"]
                )
            )

        if "fvg_mitigated" in row.index:

            mitigated = self._to_float(
                row["fvg_mitigated"]
            )

            if mitigated == 1.0:
                return 100.0

        if "fvg_rejection" in row.index:

            rejection = self._to_float(
                row["fvg_rejection"]
            )

            if rejection == 1.0:

                return self._clamp(
                    self._to_float(
                        row["fvg_rejection_strength"]
                        if "fvg_rejection_strength"
                        in row.index
                        else 50.0,
                        default=50.0,
                    )
                )

        return 0.0

    # =========================================================================
    # Direction
    # =========================================================================

    def _detect_direction(
        self,
        row: pd.Series,
    ) -> str:
        """
        Determine directional bias from existing signals.
        """

        bullish_score = 0.0
        bearish_score = 0.0

        bullish_columns = [
            "bullish_fvg",
            "bullish_bos",
            "bullish_sweep",
        ]

        bearish_columns = [
            "bearish_fvg",
            "bearish_bos",
            "bearish_sweep",
        ]

        for column in bullish_columns:

            if column in row.index:

                if self._to_float(
                    row[column]
                ) == 1.0:

                    bullish_score += 1.0

        for column in bearish_columns:

            if column in row.index:

                if self._to_float(
                    row[column]
                ) == 1.0:

                    bearish_score += 1.0

        if bullish_score > bearish_score:
            return "BULLISH"

        if bearish_score > bullish_score:
            return "BEARISH"

        return "NEUTRAL"

    # =========================================================================
    # Grade
    # =========================================================================

    @staticmethod
    def _grade(
        score: float,
    ) -> str:

        if score >= 85.0:
            return "A+"

        if score >= 75.0:
            return "A"

        if score >= 65.0:
            return "B"

        if score >= 50.0:
            return "C"

        if score > 0.0:
            return "D"

        return "NONE"

    # =========================================================================
    # Main pipeline
    # =========================================================================

    def generate(
        self,
        data: pd.DataFrame,
    ) -> pd.DataFrame:

        df = data.copy()

        self._ensure_columns(df)

        # ---------------------------------------------------------------------
        # Output columns
        # ---------------------------------------------------------------------

        df["confidence_score"] = 0.0
        df["confidence_grade"] = "NONE"
        df["confidence_direction"] = "NEUTRAL"

        df["confidence_fvg"] = 0.0
        df["confidence_displacement"] = 0.0
        df["confidence_bos"] = 0.0
        df["confidence_liquidity"] = 0.0
        df["confidence_structure"] = 0.0
        df["confidence_mitigation"] = 0.0

        df["confidence_confluence"] = 0
        df["trade_ready"] = 0

        # ---------------------------------------------------------------------
        # Process rows
        # ---------------------------------------------------------------------

        for i in range(len(df)):

            row = df.iloc[i]

            fvg_score = self._fvg_score(row)
            displacement_score = self._displacement_score(row)
            bos_score = self._bos_score(row)
            liquidity_score = self._liquidity_score(row)
            structure_score = self._structure_score(row)
            mitigation_score = self._mitigation_score(row)

            # -------------------------------------------------------------
            # Weighted score
            # -------------------------------------------------------------

            weighted_score = (
                fvg_score * self.fvg_weight
                + displacement_score
                * self.displacement_weight
                + bos_score
                * self.bos_weight
                + liquidity_score
                * self.liquidity_weight
                + structure_score
                * self.structure_weight
                + mitigation_score
                * self.mitigation_weight
            )

            final_score = (
                weighted_score
                / self.total_weight
                / 100.0
                * 100.0
            )

            final_score = self._clamp(
                final_score
            )

            # -------------------------------------------------------------
            # Confluence
            # -------------------------------------------------------------

            scores = [
                fvg_score,
                displacement_score,
                bos_score,
                liquidity_score,
                structure_score,
                mitigation_score,
            ]

            confluence = sum(
                1
                for score in scores
                if score > 0.0
            )

            direction = self._detect_direction(
                row
            )

            grade = self._grade(
                final_score
            )

            # -------------------------------------------------------------
            # Trade readiness
            # -------------------------------------------------------------

            trade_ready = 0

            if (
                final_score >= 65.0
                and confluence >= 3
                and direction != "NEUTRAL"
            ):
                trade_ready = 1

            # -------------------------------------------------------------
            # Store
            # -------------------------------------------------------------

            index = df.index[i]

            df.at[
                index,
                "confidence_score",
            ] = round(
                final_score,
                2,
            )

            df.at[
                index,
                "confidence_grade",
            ] = grade

            df.at[
                index,
                "confidence_direction",
            ] = direction

            df.at[
                index,
                "confidence_fvg",
            ] = round(
                fvg_score,
                2,
            )

            df.at[
                index,
                "confidence_displacement",
            ] = round(
                displacement_score,
                2,
            )

            df.at[
                index,
                "confidence_bos",
            ] = round(
                bos_score,
                2,
            )

            df.at[
                index,
                "confidence_liquidity",
            ] = round(
                liquidity_score,
                2,
            )

            df.at[
                index,
                "confidence_structure",
            ] = round(
                structure_score,
                2,
            )

            df.at[
                index,
                "confidence_mitigation",
            ] = round(
                mitigation_score,
                2,
            )

            df.at[
                index,
                "confidence_confluence",
            ] = confluence

            df.at[
                index,
                "trade_ready",
            ] = trade_ready

        return df


confidence_engine = ConfidenceEngine()